export const dummyData = [
  {
    id: 1,
    name: "Introduction to Emerging Technologies",
    desc: "Exploring new and evolving technologies that are shaping the future.",
    cover: "/images/introduction-to-emerging-technologies-cover.jpg",
    pdfUrl: "/images/pdf/EMERGING TECHNOLOGIES.pdf",
  },
  {
    id: 2,
    name: "General Physics Course Syllabus",
    desc: "A comprehensive syllabus for the General Physics course.",
    cover: "/images/course-syllabus-for-general-physics-cover.jpg",
    pdfUrl: "/images/pdf/General Physics.pdf",
  },
  {
    id: 3,
    name: "Inclusiveness in Higher Education",
    desc: "A course promoting inclusiveness across all disciplines in higher education.",
    cover: "/images/inclusiveness-course-cover.jpg",
    pdfUrl: "/images/pdf/INCLUSIVENESS Module(4).pdf",
  },
  {
    id: 4,
    name: "Introduction to Emerging Technologies Module",
    desc: "Detailed module on emerging technologies for students.",
    cover: "/images/introduction-to-emerging-technologies-course-module-cover.jpg",
    pdfUrl: "/images/pdf/general biology.pdf",
  },
  {
    id: 5,
    name: "General Biology (Biol. 1012)",
    desc: "Course material for General Biology (Biol. 1012).",
    cover: "/images/general-biology-cover.jpg",
    pdfUrl: "/images/pdf/general biology.pdf",
  },
  {
    id: 6,
    name: "Mathematics for Natural Sciences",
    desc: "Mathematical concepts and applications in natural sciences.",
    cover: "/images/mathematics-for-natural-sciences-cover.jpg",
    pdfUrl: "/images/pdf/Maths for Natural Sciecne.pdf",
  },
  {
    id: 7,
    name: "Mathematics for Social Sciences",
    desc: "Mathematical methods and theories applicable to social sciences.",
    cover: "/images/mathematics-for-social-sciences-cover.jpg",
    pdfUrl: "/images/pdf/general biology.pdf",
  },
  {
    id: 8,
    name: "Communicative English Language Skills II",
    desc: "Advanced skills in communicative English for academic purposes.",
    cover: "/images/communicative-english-language-skills-II-cover.jpg",
    pdfUrl: "/images/pdf/Communicative English Language Skills I.pdf",
  },
  {
    id: 9,
    name: "Moral and Citizenship Education",
    desc: "Course material on moral values and citizenship education.",
    cover: "/images/moral-and-citizenship-education-cover.jpg",
    pdfUrl: "/images/pdf/Moral and Civics Module (2).pdf",
  },
  {
    id: 10,
    name: "Introduction to Economics",
    desc: "Basic concepts and principles of economics.",
    cover: "/images/logic-short-note-cover.jpg",
    pdfUrl: "/images/pdf/Logic short reading material.pdf",
  },
];
